In [ ]:
import numpy as np 
x = np.array([[1,2], [8,7]])
y = np.array([1,0])
z = np.matmul(x, y)
#z = np.sum(y)
print(sum(z))

In [ ]:
import numpy as np
x = np.array([1,0,1])
y = np.array([0,1,1])
z = np.dot(x, y)
print(z)

1

In [ ]:
!wget 'https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb' -O data.csv

--2022-12-07 01:49:57--  https://drive.google.com/uc?export=download&id=1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb
Resolving drive.google.com (drive.google.com)... 108.177.127.139, 108.177.127.102, 108.177.127.113, ...
Connecting to drive.google.com (drive.google.com)|108.177.127.139|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/eu21aosptu4apjlomojtu9l0na780hhr/1670377725000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=43895418-6241-4cbb-b0b6-073ea0d42600 [following]
Warning: wildcards not supported in HTTP.
--2022-12-07 01:49:58--  https://doc-0g-a8-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/eu21aosptu4apjlomojtu9l0na780hhr/1670377725000/17823811839281681652/*/1-0W0PIng8b0WRYEkDRl2u4eD0QNJa6Tb?e=download&uuid=43895418-6241-4cbb-b0b6-073ea0d42600
Resolving doc-0g-a8-docs.googleusercontent.com (doc-0g-a8-docs.googleusercontent.com)... 142.250.145.132, 2a00:1450:4013:c14::84
Connecting to doc-0g-a8-docs.googleusercontent.com (doc-0g-a8-docs.googleusercontent.com)|142.250.145.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1683 (1.6K) [text/csv]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.64K  --.-KB/s    in 0s

2022-12-07 01:49:59 (55.4 MB/s) - ‘data.csv’ saved [1683/1683]

In [ ]:
import numpy as np
import random

trans_np = np.genfromtxt("data.csv", delimiter=',')
for i in range(0,3): print(f"{str(trans_np[random.randint(1,27)][0:])}")

[ 39.        nan  46.     72.     67.     72.5    82.5    95.    100.
  84.        nan  76.325  75.725]
[ 36.          nan  49.      33.      56.      70.      82.5    100.
  85.      74.          nan  67.6125  69.15  ]
[ 36.          nan  49.      33.      56.      70.      82.5    100.
  85.      74.          nan  67.6125  69.15  ]

In [ ]:
import numpy as np
from pprint import pprint
import random

trans_np = np.genfromtxt("data.csv", delimiter=',')
sum(trans_np[9][2:])
trans_np[9][2:].sum()
pprint(f"Wrong  : {trans_np[9:][2]}", width = 200, compact=True)
print("Wrong  : " + str(trans_np[9:][2]))
print(f"Correct : {trans_np[9:,2]}")
print(f"Correct : {trans_np[9:,2]}")

print(trans_np.shape)
print(trans_np.ndim)
print(trans_np.size)
print(len(trans_np))

print(f"List 2, 5 8 \n scores : {trans_np[[2,5,8],2:]}")
print("=============================")
for i in range(0,3): print(str(trans_np[random.randint(1,28)][0:]))

'Wrong  : [11.       nan 19.    40.     6.    35.    37.5   38.5   60.    24.\n    nan 36.475 34.475]'
Wrong  : [11.       nan 19.    40.     6.    35.    37.5   38.5   60.    24.
    nan 36.475 34.475]
Correct : [88. 54. 19. 51. 68. 60. 45. 68. 32. 57. 80. 68. 69. 57. 39. 49. 59. 64.
 46.]
Correct : [88. 54. 19. 51. 68. 60. 45. 68. 32. 57. 80. 68. 69. 57. 39. 49. 59. 64.
 46.]
(28, 13)
2
364
28
List 2, 5 8
 scores : [[ 75.      98.      94.      87.5     90.      97.5    100.      96.
       nan  91.075   90.8   ]
 [ 55.      29.      69.      62.5     75.      66.5     92.5     86.
       nan  64.6     65.275 ]
 [ 54.      66.      35.      65.      80.      98.      92.5     92.
       nan  70.625   70.7625]]
=============================
[ 6.         nan 74.     81.     80.     82.5    90.     93.     95.
 98.         nan 84.6875 84.075 ]
[37.         nan 59.     79.     84.     70.     80.     93.5    90.
 88.         nan 79.1375 81.375 ]
[ 7.         nan 69.     87.     70.     67.5    85.     95.     90.
 84.         nan 80.5875 80.925 ]

In [ ]:
x = [5, 3, 8, 6]
y = [12, 13]
x.append(7)
print(x)
x.extend(y)
print(x)
x.insert(1, 7)
print(x)
x.insert(1,['a','m'])
print(x)
x.pop()
print(x)
x.remove(3)
print(x)
x.reverse()
print(x)
x.sort()
print(x)

[5, 3, 8, 6, 7]
[5, 3, 8, 6, 7, 12, 13]
[5, 7, 3, 8, 6, 7, 12, 13]
[5, ['a', 'm'], 7, 3, 8, 6, 7, 12, 13]
[5, ['a', 'm'], 7, 3, 8, 6, 7, 12]
[5, ['a', 'm'], 7, 8, 6, 7, 12]
[12, 7, 6, 8, 7, ['a', 'm'], 5]

In [ ]:
mylist=[42,'apple',u'unicode apple',5234656]
print(mylist)
mylist[2]='banana'
print(mylist)
mylist[3]=[['item1','item2'],['item3','item4']]
print(mylist)
#mylist.sort()
print(mylist)
print(mylist.pop())
mynewlist=[x*2 for x in range(0,5)]
print(mynewlist)

[42, 'apple', 'unicode apple', 5234656]
[42, 'apple', 'banana', 5234656]
[42, 'apple', 'banana', [['item1', 'item2'], ['item3', 'item4']]]
[42, 'apple', 'banana', [['item1', 'item2'], ['item3', 'item4']]]
[['item1', 'item2'], ['item3', 'item4']]
[0, 2, 4, 6, 8]

In [ ]:
print("Hello Python")

Hello Python

In [ ]:
str=input()
x1=len(str)
print(str[x1::-1])

pigjraojgroejapo
opajeorgjoarjgip

In [ ]:
count=0
for num in range(1000,10000):
   if num > 1:
       for i in range(2,num):
           if (num % i) == 0:
               break
       else:
           #print(num,end="")
           count=count+1
print(count)

1061

In [ ]:
str=input()
x1=len(str)
print(x1)

wjio jfioejqoi jefoi jwioef joqw
33

In [ ]:
str=list(input())
count=0
for i in range(0,len(str)):
  if str[i].isdigit():
    count=count+1
print(count)

ag48ad98g4f98da4g
8

In [ ]:
import random, string
print(random.choice(string.ascii_letters))
print(random.choice(string.ascii_uppercase)+random.choice(string.ascii_lowercase))
print(random.choice(string.ascii_letters)+random.choice(string.ascii_letters)+random.choice(string.ascii_letters)+random.choice(string.ascii_letters)+random.choice(string.ascii_letters))
print(chr(random.randint(32,126))+chr(random.randint(32,126))+chr(random.randint(32,126))+chr(random.randint(32,126))+chr(random.randint(32,126)))
for i in range(random.randint(2,7)):
  print(chr(random.randint(32,126)),end="")
string.degre = ["PHD","Master","Bachelor"]
print("\n"+random.choice(string.degre))

s
Cb
lcwqN
Wlos|
A{J[-
PHD

In [ ]:
import random, string
string.degre1 = ["1","2","3","4","5","6","7","8","9","0"]
string.degre2 = ["!","@","#","$","@","&","%"]
print(random.choice(string.ascii_uppercase)+random.choice(string.ascii_lowercase)+random.choice(string.degre1)+random.choice(string.degre2),end="")
for i in range(random.randint(4,100)):
  print(chr(random.randint(32,126)),end="")

Ak6%roIg5@O[?-k+;rHiQ{vQ\plUaZW8[( wGuu_t.8V?PqMP<$Vg x}G(!EN*\c> hg1Moz7CE~xgb k4.J%M{I]7hTc#

In [ ]:
%cd  '/content/drive/MyDrive/Courses/Linux_111'
!pwd

[Errno 2] No such file or directory: '/content/drive/MyDrive/Courses/Linux_111'
/content
/content

In [ ]:
import numpy as np
from pprint import pprint
import random

trans_np = np.genfromtxt("data.csv", delimiter=',')
#for i in range(0,3): print(f"{str(trans_np[random.randint(1,10)][0:])}")

trans_np = np.genfromtxt("data.csv", delimiter=',')
sum(trans_np[0][2:])
trans_np[0][2:].sum()
pprint(f"Wrong  : {trans_np[0:][2]}", width = 200, compact=True)
#print("Wrong  : " + str(trans_np[0:][2]))
print(f"Correct : {trans_np[0:,2]}")
print(f"Correct : {trans_np[0:,2]}")

print(trans_np.shape)
print(trans_np.ndim)
print(trans_np.size)
print(len(trans_np))

print(f"List 2, 5 8 \n scores : {trans_np[[2,5,8],2:]}")
print("=============================")
for i in range(0,3): print(str(trans_np[random.randint(1,10)][0:]))

'Wrong  : [  2.        nan  75.     98.     94.     87.5    90.     97.5   100.\n  96.        nan  91.075  90.8  ]'
Correct : [nan 77. 75. 74. 40. 55. 74. 69. 54. 88. 54. 19. 51. 68. 60. 45. 68. 32.
 57. 80. 68. 69. 57. 39. 49. 59. 64. 46.]
Correct : [nan 77. 75. 74. 40. 55. 74. 69. 54. 88. 54. 19. 51. 68. 60. 45. 68. 32.
 57. 80. 68. 69. 57. 39. 49. 59. 64. 46.]
(28, 13)
2
364
28
List 2, 5 8
 scores : [[ 75.      98.      94.      87.5     90.      97.5    100.      96.
       nan  91.075   90.8   ]
 [ 55.      29.      69.      62.5     75.      66.5     92.5     86.
       nan  64.6     65.275 ]
 [ 54.      66.      35.      65.      80.      98.      92.5     92.
       nan  70.625   70.7625]]
=============================

TypeError: ignored

In [ ]:
import numpy as np
from pprint import pprint
import random

count=0
trans_np = np.genfromtxt("data.csv", delimiter=',')
print(trans_np)
trans_np[:,8] < 60
#if trans_np[:,8] < 60:
  #count=count+1

[[     nan      nan      nan      nan      nan      nan      nan      nan
       nan      nan      nan      nan      nan]
 [  1.          nan  77.      89.      89.      95.     100.     100.
   97.5     90.          nan  91.525   91.075 ]
 [  2.          nan  75.      98.      94.      87.5     90.      97.5
  100.      96.          nan  91.075   90.8   ]
 [  3.          nan  74.      90.      73.      85.      97.5     95.
   92.5     92.          nan  86.2875  85.725 ]
 [  4.          nan  40.      23.      42.      40.      32.5     40.5
   55.      26.          nan  41.075   38.7375]
 [  5.          nan  55.      29.      69.      62.5     75.      66.5
   92.5     86.          nan  64.6     65.275 ]
 [  6.          nan  74.      81.      80.      82.5     90.      93.
   95.      98.          nan  84.6875  84.075 ]
 [  7.          nan  69.      87.      70.      67.5     85.      95.
   90.      84.          nan  80.5875  80.925 ]
 [  8.          nan  54.      66.      35.      65.      80.      98.
   92.5     92.          nan  70.625   70.7625]
 [  9.          nan  88.      87.     100.      97.5     95.     100.
  100.     100.          nan  94.3125  96.9   ]
 [ 10.          nan  54.      79.      75.      75.      92.      88.
   95.      86.          nan  79.45    78.8125]
 [ 11.          nan  19.      40.       6.      35.      37.5     38.5
   60.      24.          nan  36.475   34.475 ]
 [ 12.          nan  51.      45.      71.      70.      67.5     57.5
   65.      72.          nan  61.4     60.5875]
 [ 13.          nan  68.      76.      82.      75.      95.     100.
  100.      98.          nan  84.6     87.05  ]
 [ 26.          nan  60.      73.      61.      60.      75.      76.5
   92.5     70.          nan  71.8875  74.1125]
 [ 27.          nan  45.      63.      67.      75.      87.5     90.5
   92.5     90.          nan  74.075   74.175 ]
 [ 28.          nan  68.      83.      87.      97.5     90.      97.5
  100.      98.          nan  88.15    88.6875]
 [ 29.          nan  32.      58.      69.      82.5     87.5     72.5
   92.5     74.          nan  70.3125  71.35  ]
 [ 30.          nan  57.      86.      66.      67.5     82.5     86.5
   92.5     86.          nan  77.1375  76.525 ]
 [ 31.          nan  80.      78.      83.      80.      97.5     97.5
   97.5    100.          nan  87.075   88.4875]
 [ 32.          nan  68.      92.      75.      80.      85.      81.5
   97.5     84.          nan  82.8125  85.4   ]
 [ 33.          nan  69.      53.      54.      55.      75.      90.5
   82.5     86.          nan  68.9875  69.7125]
 [ 34.          nan  57.      42.      67.      75.      77.5     87.
   87.5     66.          nan  70.2875  69.    ]
 [ 35.          nan  39.      34.      26.      75.      72.5     91.5
   90.      78.          nan  61.575   61.25  ]
 [ 36.          nan  49.      33.      56.      70.      82.5    100.
   85.      74.          nan  67.6125  69.15  ]
 [ 37.          nan  59.      79.      84.      70.      80.      93.5
   90.      88.          nan  79.1375  81.375 ]
 [ 38.          nan  64.      92.      74.      75.     100.      86.
   97.5     78.          nan  83.9     84.4875]
 [ 39.          nan  46.      72.      67.      72.5     82.5     95.
  100.      84.          nan  76.325   75.725 ]]

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
import csv
# 開啟 CSV 檔案
from pprint import pprint
with open('data.csv', newline='') as csvfile:
  # 讀取 CSV 檔案內容
  rows = csv.reader(csvfile)
  scores_list = list(rows)
  #pprint(scores_list, compact =True)
  #pprint(scores_list[i][1])
  #pprint(sum(map(lambda x: float(x),scores_list[9][2:10])))
  #sub="Lin"
  count=0
  for i in range(1,28):
    #print(scores_list[i][1])
    if "Lin" in scores_list[i][1]:
      count=count+1
  print(count)

'Nicola Chu'
Nicola Chu
Karen Wu
Fiona Wu
Susan Lu
Claire Lin
Sharon Chiu
Angela Chen
Gillian Lin
Julie Chen
Michelle Lin
Jacqueline
Amanda
Tracy Wu
David Lin
John Chu
Paul Chen
Mark Wu
James Lin
Andrew Wang
Scott Wu
Steven Yang
Robert Chen
Stephen Yang
William Lin
Michael Chu
Kevin Chen
Leo Su
6

In [ ]:
import csv
from pprint import pprint
with open('data.csv', newline='') as csvfile:
  rows = csv.reader(csvfile)
  scores_list = list(rows)
  count=0
  for i in range(1,28):
    #print(scores_list[i][7])
    if float(scores_list[i][7]) < 60 :
      count=count+1
  print(count)

3

---

In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
print(df)
display(df)
display("Math")
#display(df[6])
display(df.iloc[0:10:2,1:3])
display(df.loc[0:10:2,"Math"])
display(df.loc[0:10:2,["Math","Chinese","English"]])

display(df.loc[df.loc[:,"ID"] == 13,["Math","Chinese","English"]])
selected = df.loc[df.loc[:,"ID"] == 13,["Math","Chinese","English"]]

engdata=df.loc[df['English']<60,"Full Name"]
print(engdata)

df.sort_values(by='English').loc[:,"Full Name"]

    ID     Full Name  Chinese  English  Math  Physical and chemical  \
0    1    Nicola Chu       77       89    89                   95.0
1    2      Karen Wu       75       98    94                   87.5
2    3      Fiona Wu       74       90    73                   85.0
3    4      Susan Lu       40       23    42                   40.0
4    5    Claire Lin       55       29    69                   62.5
5    6   Sharon Chiu       74       81    80                   82.5
6    7   Angela Chen       69       87    70                   67.5
7    8   Gillian Lin       54       66    35                   65.0
8    9    Julie Chen       88       87   100                   97.5
9   10  Michelle Lin       54       79    75                   75.0
10  11    Jacqueline       19       40     6                   35.0
11  12        Amanda       51       45    71                   70.0
12  13      Tracy Wu       68       76    82                   75.0
13  26     David Lin       60       73    61                   60.0
14  27      John Chu       45       63    67                   75.0
15  28     Paul Chen       68       83    87                   97.5
16  29       Mark Wu       32       58    69                   82.5
17  30     James Lin       57       86    66                   67.5
18  31   Andrew Wang       80       78    83                   80.0
19  32      Scott Wu       68       92    75                   80.0
20  33   Steven Yang       69       53    54                   55.0
21  34   Robert Chen       57       42    67                   75.0
22  35  Stephen Yang       39       34    26                   75.0
23  36   William Lin       49       33    56                   70.0
24  37   Michael Chu       59       79    84                   70.0
25  38    Kevin Chen       64       92    74                   75.0
26  39        Leo Su       46       72    67                   72.5

    Geophaphy  History  Physics  Civics Bonus   Final1   Final2
0       100.0    100.0     97.5      90     ?  91.5250  91.0750
1        90.0     97.5    100.0      96     ?  91.0750  90.8000
2        97.5     95.0     92.5      92     ?  86.2875  85.7250
3        32.5     40.5     55.0      26     ?  41.0750  38.7375
4        75.0     66.5     92.5      86     ?  64.6000  65.2750
5        90.0     93.0     95.0      98     ?  84.6875  84.0750
6        85.0     95.0     90.0      84     ?  80.5875  80.9250
7        80.0     98.0     92.5      92     ?  70.6250  70.7625
8        95.0    100.0    100.0     100     ?  94.3125  96.9000
9        92.0     88.0     95.0      86     ?  79.4500  78.8125
10       37.5     38.5     60.0      24     ?  36.4750  34.4750
11       67.5     57.5     65.0      72     ?  61.4000  60.5875
12       95.0    100.0    100.0      98     ?  84.6000  87.0500
13       75.0     76.5     92.5      70     ?  71.8875  74.1125
14       87.5     90.5     92.5      90     ?  74.0750  74.1750
15       90.0     97.5    100.0      98     ?  88.1500  88.6875
16       87.5     72.5     92.5      74     ?  70.3125  71.3500
17       82.5     86.5     92.5      86     ?  77.1375  76.5250
18       97.5     97.5     97.5     100     ?  87.0750  88.4875
19       85.0     81.5     97.5      84     ?  82.8125  85.4000
20       75.0     90.5     82.5      86     ?  68.9875  69.7125
21       77.5     87.0     87.5      66     ?  70.2875  69.0000
22       72.5     91.5     90.0      78     ?  61.5750  61.2500
23       82.5    100.0     85.0      74     ?  67.6125  69.1500
24       80.0     93.5     90.0      88     ?  79.1375  81.3750
25      100.0     86.0     97.5      78     ?  83.9000  84.4875
26       82.5     95.0    100.0      84     ?  76.3250  75.7250

,ID,Full Name,Chinese,English,Math,Physical and chemical,Geophaphy,History,Physics,Civics,Bonus,Final1,Final2
0,1,Nicola Chu,77,89,89,95.0,100.0,100.0,97.5,90,?,91.5250,91.0750
1,2,Karen Wu,75,98,94,87.5,90.0,97.5,100.0,96,?,91.0750,90.8000
2,3,Fiona Wu,74,90,73,85.0,97.5,95.0,92.5,92,?,86.2875,85.7250
3,4,Susan Lu,40,23,42,40.0,32.5,40.5,55.0,26,?,41.0750,38.7375
4,5,Claire Lin,55,29,69,62.5,75.0,66.5,92.5,86,?,64.6000,65.2750
5,6,Sharon Chiu,74,81,80,82.5,90.0,93.0,95.0,98,?,84.6875,84.0750
6,7,Angela Chen,69,87,70,67.5,85.0,95.0,90.0,84,?,80.5875,80.9250
7,8,Gillian Lin,54,66,35,65.0,80.0,98.0,92.5,92,?,70.6250,70.7625
8,9,Julie Chen,88,87,100,97.5,95.0,100.0,100.0,100,?,94.3125,96.9000
9,10,Michelle Lin,54,79,75,75.0,92.0,88.0,95.0,86,?,79.4500,78.8125
10,11,Jacqueline,19,40,6,35.0,37.5,38.5,60.0,24,?,36.4750,34.4750
11,12,Amanda,51,45,71,70.0,67.5,57.5,65.0,72,?,61.4000,60.5875
12,13,Tracy Wu,68,76,82,75.0,95.0,100.0,100.0,98,?,84.6000,87.0500
13,26,David Lin,60,73,61,60.0,75.0,76.5,92.5,70,?,71.8875,74.1125
14,27,John Chu,45,63,67,75.0,87.5,90.5,92.5,90,?,74.0750,74.1750
15,28,Paul Chen,68,83,87,97.5,90.0,97.5,100.0,98,?,88.1500,88.6875
16,29,Mark Wu,32,58,69,82.5,87.5,72.5,92.5,74,?,70.3125,71.3500
17,30,James Lin,57,86,66,67.5,82.5,86.5,92.5,86,?,77.1375,76.5250
18,31,Andrew Wang,80,78,83,80.0,97.5,97.5,97.5,100,?,87.0750,88.4875
19,32,Scott Wu,68,92,75,80.0,85.0,81.5,97.5,84,?,82.8125,85.4000
20,33,Steven Yang,69,53,54,55.0,75.0,90.5,82.5,86,?,68.9875,69.7125
21,34,Robert Chen,57,42,67,75.0,77.5,87.0,87.5,66,?,70.2875,69.0000
22,35,Stephen Yang,39,34,26,75.0,72.5,91.5,90.0,78,?,61.5750,61.2500
23,36,William Lin,49,33,56,70.0,82.5,100.0,85.0,74,?,67.6125,69.1500
24,37,Michael Chu,59,79,84,70.0,80.0,93.5,90.0,88,?,79.1375,81.3750
25,38,Kevin Chen,64,92,74,75.0,100.0,86.0,97.5,78,?,83.9000,84.4875
26,39,Leo Su,46,72,67,72.5,82.5,95.0,100.0,84,?,76.3250,75.7250

'Math'

     Full Name  Chinese
0   Nicola Chu       77
2     Fiona Wu       74
4   Claire Lin       55
6  Angela Chen       69
8   Julie Chen       88

0      89
2      73
4      69
6      70
8     100
10      6
Name: Math, dtype: int64

    Math  Chinese  English
0     89       77       89
2     73       74       90
4     69       55       29
6     70       69       87
8    100       88       87
10     6       19       40

    Math  Chinese  English
12    82       68       76

3         Susan Lu
4       Claire Lin
10      Jacqueline
11          Amanda
16         Mark Wu
20     Steven Yang
21     Robert Chen
22    Stephen Yang
23     William Lin
Name: Full Name, dtype: object

3         Susan Lu
4       Claire Lin
23     William Lin
22    Stephen Yang
10      Jacqueline
21     Robert Chen
11          Amanda
20     Steven Yang
16         Mark Wu
14        John Chu
7      Gillian Lin
26          Leo Su
13       David Lin
12        Tracy Wu
18     Andrew Wang
9     Michelle Lin
24     Michael Chu
5      Sharon Chiu
15       Paul Chen
17       James Lin
8       Julie Chen
6      Angela Chen
0       Nicola Chu
2         Fiona Wu
25      Kevin Chen
19        Scott Wu
1         Karen Wu
Name: Full Name, dtype: object

In [ ]:
import csv
from pprint import pprint
with open('data.csv', newline='') as csvfile:
  rows = csv.reader(csvfile)
  scores_list = list(rows)
  for i in range(1,28):
    if (float(scores_list[i][3]) >= 80) & (float(scores_list[i][8]) >= 80) :
      print(scores_list[i][1])

Nicola Chu
Karen Wu
Fiona Wu
Sharon Chiu
Angela Chen
Julie Chen
Paul Chen
James Lin
Scott Wu
Kevin Chen

In [ ]:
import requests

def crawl_stock(stock_id):
  url = "http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=20221214&stockNo=" + stock_id
  resp = requests.get(url)
  if resp.status_code != 200:
    return None
  else:
    return resp.json()

# 範例：抓取台積電的股票資料
stock_data = crawl_stock("2330")
print(stock_data)

{'stat': 'OK', 'date': '20221214', 'title': '111年12月 2330 台積電           各日成交資訊', 'fields': ['日期', '成交股數', '成交金額', '開盤價', '最高價', '最低價', '收盤價', '漲跌價差', '成交筆數'], 'data': [['111/12/01', '43,684,491', '21,976,936,461', '506.00', '508.00', '498.50', '498.50', '+8.50', '46,181'], ['111/12/02', '29,909,021', '14,745,810,388', '490.00', '497.00', '490.00', '492.50', '-6.00', '31,799'], ['111/12/05', '33,048,153', '16,272,219,716', '491.50', '497.50', '489.00', '489.00', '-3.50', '31,739'], ['111/12/06', '44,964,237', '21,703,863,181', '488.00', '489.00', '478.00', '478.00', '-11.00', '44,448'], ['111/12/07', '39,978,821', '19,128,832,587', '477.00', '485.50', '475.00', '475.00', '-3.00', '43,603'], ['111/12/08', '28,348,573', '13,366,736,635', '475.00', '475.00', '467.00', '471.50', '-3.50', '45,114'], ['111/12/09', '28,903,860', '13,881,674,073', '478.00', '484.50', '476.00', '481.50', '+10.00', '25,790'], ['111/12/12', '24,064,002', '11,435,789,974', '476.50', '478.00', '473.50', '475.00', '-6.50', '34,393'], ['111/12/13', '36,028,109', '17,034,191,389', '473.00', '476.00', '471.00', '471.50', '-3.50', '36,559']], 'notes': ['符號說明:+/-/X表示漲/跌/不比價', '當日統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。', 'ETF證券代號第六碼為K、M、S、C者，表示該ETF以外幣交易。', '權證證券代號可重複使用，權證顯示之名稱係目前存續權證之簡稱。']}

In [ ]:
#1. 如何推算出 Final 1 方式的成績單的加權公式及加分?
import numpy as np
#寫出係數矩陣 A
A = np.array([
    [77,89,89,95,100,100,97.5,90],
    [75,98,94,87.5,90,97.5,100,96],
    [74,90,73,85,97.5,95,92.5,92],
    [40,23,42,40,32.5,40.5,55,26],
    [55,29,69,62.5,75,66.5,92.5,86],
    [74,81,80,82.5,90,93,95,98],
    [69,87,70,67.5,85,95,90,84],
    [54,66,35,65,80,98,92.5,92],
    [88,87,100,97.5,95,100,100,100],
    [54,79,75,75,92,88,95,86],
    [19,40,6,35,37.5,38.5,60,24],
    [51,45,71,70,67.5,57.5,65,72],
    [68,76,82,75,95,100,100,98],
    [60,73,61,60,75,76.5,92.5,70],
    [45,63,67,75,87.5,90.5,92.5,90],
    [32,58,69,82.5,87.5,72.5,92.5,74],
    [57,86,66,67.5,82.5,86.5,92.5,86],
    [80,78,83,80,97.5,97.5,97.5,100],
    [68,92,75,80,85,81.5,97.5,84],
    [69,53,54,55,75,90.5,82.5,86],
    [57,42,67,75,77.5,87,87.5,66],
    [39,34,26,75,72.5,91.5,90,78],
    [49,33,56,70,82.5,100,85,74],
    [59,79,84,70,80,93.5,90,88],
    [64,92,74,75,100,86,97.5,78],
    [46,72,67,72.5,82.5,95,100,84]
])
# 寫出常數矩陣 B
B = np.array([91.525,91.075,86.2875,41.075,64.6,84.6875,80.5875,70.625,94.3125,79.45,36.475,61.4,84.6,71.8875,74.075,88.15,70.3125,77.1375,87.075,82.8125,68.9875,70.2875,61.575,67.6125,79.1375,83.9,76.325]).reshape(27, 1)
# 找出係數矩陣的反矩陣 A_inv
A_inv = np.linalg.inv(A)
# 將 A_inv 與 B 相乘，即可得到解答
ans = A_inv.dot(B)
print(ans)